name: coffe_bee_order
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  carousel_slider: ^4.2.1
  image_picker: ^0.8.7+5
  nb_utils: ^5.0.8
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  animated_text_kit: ^4.2.2
  otp_text_field: ^1.1.3
  otp_timer_button: ^1.1.0
  scrollable_positioned_list: ^0.3.8
  dio: ^5.1.2
  audioplayers: ^4.1.0
  intl: ^0.18.1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.3
  firebase_crashlytics: ^3.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

#  flutter_icons:
#    android: true
#    ios: true
#    image_path: "assets/image/logo.png"
#    adaptive_icon_background: "#ffffff"


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/image/



